# Generated by Django 3.0.8 on 2020-09-28 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200928_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 28, 13, 20, 54, 324235, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
